[package]
name = "circuits"
type = "bin"
authors = [""]

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
jwt = { tag = "v0.5.0", git = "https://github.com/zkemail/noir-jwt" }
